services:
  dynamic_qr:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    volumes: 
      - .:/usr/src/app
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=serv
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - REDIS_URL=redis_instance
      - REDIS_PORT=6379
    command: bun --watch run index.ts
    tty: true

  redis_instance:
    image: redis:8.0-M03-alpine
    ports:
      - "6379:6379"
    
  postgres:
    image: postgres:17
    env_file: .env
    volumes:
    - ./postgres_data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
